all: main.c  Sources/Heapsort.c Sources/Ordenacao_simples.c Sources/Quicksort.c  Sources/ShellSort.c Sources/TAD_dicionario.c Sources/TAD_lista.c Sources/TADPalavra.c
	gcc  main.c  Sources/Heapsort.c Sources/Ordenacao_simples.c Sources/Quicksort.c  Sources/ShellSort.c Sources/TAD_dicionario.c Sources/TAD_lista.c Sources/TADPalavra.c -o exec

clang: main.c
	clang main.c -o EXEC_CLANG Sources/PBN.c Sources/Heapsort.c Sources/Ordenacao_simples.c Sources/Quicksort.c  Sources/ShellSort.c Sources/TAD_dicionario.c Sources/TAD_lista.c Sources/TADPalavra.c

run: exec
	./exec

