all: main.c  Sources/Heapsort.c Sources/Ordenacao_simples.c Sources/Quicksort.c  Sources/ShellSort.c
	gcc  main.c  Sources/Heapsort.c Sources/Ordenacao_simples.c Sources/Quicksort.c  Sources/ShellSort.c -o exec

clang: main.c
	clang main.c -o EXEC_CLANG Sources/PBN.c

run: exec
	./exec

